[project]
name = "sitemap-mcp-server"
version = "0.1.4"
description = "MCP server for fetching, parsing and crawling sitemaps of a given website"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.6.0",
    "pydantic>=2.11.3",
    "ultimate-sitemap-parser>=1.3.1",
]
